### ISSUE TITLE
Widget doesn't load

### ISSUE THREAD

**Issue by sekib** [AbhinavRajesh/Chatbotish#4]
**Describe the bug**
Widget doesn't load when using localhost:3000

**To Reproduce**
1. create simple express.js project (e.g. express express-locallibrary-tutorial --view=pug)
2. add \<link\> and <script> to index.html as described 
3. start server on localhost:3000 and load the page in browser
4. No widget is being initialized.

** Screenshot **
<img width="603" alt="Screenshot 2021-09-15 at 22 21 16" src="https://user-images.githubusercontent.com/679724/133505764-25adebfa-bf07-49f5-9e4e-62092bc6a05d.png">

**Expected behavior**
Widget should be visible.

**Comment by AbhinavRajesh** [comment]
Hey @sekib, I just looked up your project here and turns out you have entered a url(http://localhost:3000) instead of domain name(localhost). 

To fix this go to:
Dashboard -> Select the Project -> Settings Tab -> Edit Project
And  change the domain from "http://localhost:3000" to just "localhost"

This should fix this issue. If you need any further assistance reopen this issue, I would be more than happy to help you :)

**Comment by sekib** [comment]
@AbhinavRajesh Thanks mate, works like a charm!

Btw. you have a very cool blog.

**Comment by AbhinavRajesh** [comment]
Thank you @sekib . Glad it helped :)
